/**
 * Language Mappings & Query Dictionaries for Multilingual Entertainment
 * Supports 10+ Indian & Global Languages
 */

export const ENTERTAINMENT_LANGUAGES = {
  ta: {
    code: "ta",
    name: "Tamil",
    nativeName: "தமிழ்",
    flag: "🇮🇳",
    musicQueries: {
      latest: "Tamil latest songs 2025 2026",
      trending: "Tamil trending viral hits",
      popular: "Tamil all time chartbusters",
      melodies: "Tamil melody hits",
      playlists: "Top Tamil Hits Playlist",
      artists: ["Anirudh Ravichander", "A.R. Rahman", "Ilaiyaraaja", "Sid Sriram", "Yuvan Shankar Raja", "Santhosh Narayanan", "D. Imman", "Sean Roldan", "Harris Jayaraj"],
    },
    videoQueries: {
      trending: "Tamil trending entertainment videos",
      latest: "Tamil latest comedy scenes and trailers",
      comedy: "Tamil standup comedy and trending jokes",
      mindfulness: "Tamil guided meditation and stress relief",
      musicVideos: "Tamil latest official music videos",
      shorts: "Tamil entertainment shorts viral",
    },
    memeSources: {
      subreddits: ["tamilmemes", "kollywood", "Chennai", "PlipPlip"],
      searchTerms: ["tamil memes", "tamil comedy memes", "tamil cinema vadivelu memes", "tamil relatable memes"],
    },
  },
  en: {
    code: "en",
    name: "English",
    nativeName: "English",
    flag: "🌐",
    musicQueries: {
      latest: "Top English pop latest releases",
      trending: "Global Billboard Top Hits",
      popular: "All time pop chartbusters",
      melodies: "Acoustic chill pop ballads",
      playlists: "Today's Top Hits Global",
      artists: ["Taylor Swift", "Ed Sheeran", "The Weeknd", "Billie Eilish", "Dua Lipa", "Post Malone", "Bruno Mars", "Coldplay", "Adele"],
    },
    videoQueries: {
      trending: "Trending global entertainment videos",
      latest: "Latest movie trailers and celebrity interviews",
      comedy: "Best standup comedy specials clips",
      mindfulness: "5 minute guided breathing and meditation",
      musicVideos: "Official trending pop music videos",
      shorts: "Viral comedy shorts",
    },
    memeSources: {
      subreddits: ["memes", "wholesomememes", "me_irl", "dankmemes"],
      searchTerms: ["funny memes", "relatable memes", "wholesome memes", "college memes"],
    },
  },
  hi: {
    code: "hi",
    name: "Hindi",
    nativeName: "हिन्दी",
    flag: "🇮🇳",
    musicQueries: {
      latest: "Bollywood latest songs",
      trending: "Hindi trending viral songs",
      popular: "Bollywood all time romantic hits",
      melodies: "Arijit Singh soulful melodies",
      playlists: "Bollywood Top 50 Playlist",
      artists: ["Arijit Singh", "Shreya Ghoshal", "Pritam", "Neha Kakkar", "Jubin Nautiyal", "Vishal-Shekhar", "Badshah", "Atif Aslam", "Sachin-Jigar"],
    },
    videoQueries: {
      trending: "Hindi trending entertainment videos",
      latest: "Bollywood movie trailers and latest updates",
      comedy: "Hindi standup comedy clips",
      mindfulness: "Hindi meditation aur man ki shanti",
      musicVideos: "Latest Hindi official music videos",
      shorts: "Hindi comedy viral shorts",
    },
    memeSources: {
      subreddits: ["indiameme", "desimemes", "IndianDankMemes", "bakchodi"],
      searchTerms: ["hindi memes", "bollywood memes", "funny desi memes", "relatable hindi memes"],
    },
  },
  te: {
    code: "te",
    name: "Telugu",
    nativeName: "తెలుగు",
    flag: "🇮🇳",
    musicQueries: {
      latest: "Tollywood latest songs",
      trending: "Telugu trending chartbusters",
      popular: "Telugu all time super hits",
      melodies: "Telugu heart touching melody songs",
      playlists: "Top Telugu Hits Playlist",
      artists: ["Sid Sriram", "SS Thaman", "Devi Sri Prasad", "Anurag Kulkarni", "Ram Miriyala", "Armaan Malik", "Mangli", "Shreya Ghoshal"],
    },
    videoQueries: {
      trending: "Telugu trending entertainment",
      latest: "Tollywood movie trailers and updates",
      comedy: "Brahmanandam Telugu comedy scenes",
      mindfulness: "Telugu guided meditation peace of mind",
      musicVideos: "Telugu latest video songs",
      shorts: "Telugu viral entertainment shorts",
    },
    memeSources: {
      subreddits: ["Ni_Bondha", "tollywood", "TeluguMemes"],
      searchTerms: ["telugu memes", "brahmanandam memes", "tollywood funny memes", "telugu youth memes"],
    },
  },
  ml: {
    code: "ml",
    name: "Malayalam",
    nativeName: "മലയാളം",
    flag: "🇮🇳",
    musicQueries: {
      latest: "Malayalam latest movie songs",
      trending: "Mollywood trending viral tracks",
      popular: "Malayalam evergreen melodies",
      melodies: "Peaceful Malayalam acoustic melodies",
      playlists: "Top Malayalam Hits Playlist",
      artists: ["Sushin Shyam", "Hesham Abdul Wahab", "K.J. Yesudas", "K.S. Chithra", "Shaan Rahman", "Gopi Sundar", "Vineeth Sreenivasan"],
    },
    videoQueries: {
      trending: "Malayalam trending entertainment",
      latest: "Malayalam movie scenes and trailers",
      comedy: "Malayalam comedy clips and skits",
      mindfulness: "Malayalam meditation and positive energy",
      musicVideos: "Malayalam latest official video songs",
      shorts: "Malayalam funny shorts",
    },
    memeSources: {
      subreddits: ["KeralaRaza", "Lal_Salaam", "Kerala"],
      searchTerms: ["malayalam memes", "troll malayalam", "salim kumar memes", "kerala memes"],
    },
  },
  kn: {
    code: "kn",
    name: "Kannada",
    nativeName: "ಕನ್ನಡ",
    flag: "🇮🇳",
    musicQueries: {
      latest: "Sandalwood latest songs",
      trending: "Kannada trending songs",
      popular: "Kannada all time hits",
      melodies: "Kannada romantic melody songs",
      playlists: "Top Kannada Hits Playlist",
      artists: ["Sanjith Hegde", "Ravi Basrur", "Vijay Prakash", "Arjun Janya", "Charan Raj", "C. Ashwath"],
    },
    videoQueries: {
      trending: "Kannada trending entertainment videos",
      latest: "Kannada movie trailers and updates",
      comedy: "Kannada comedy scenes and standup",
      mindfulness: "Kannada guided meditation dhyana",
      musicVideos: "Kannada latest official video songs",
      shorts: "Kannada entertainment shorts",
    },
    memeSources: {
      subreddits: ["kannadamemes", "bangalore", "kannada"],
      searchTerms: ["kannada memes", "troll sandalwood", "kannada comedy memes"],
    },
  },
  bn: {
    code: "bn",
    name: "Bengali",
    nativeName: "বাংলা",
    flag: "🇮🇳",
    musicQueries: {
      latest: "Bengali latest film songs",
      trending: "Bengali trending songs",
      popular: "Bengali modern songs and Rabindra Sangeet",
      melodies: "Sweet Bengali melody hits",
      playlists: "Top Bengali Songs Playlist",
      artists: ["Arijit Singh", "Anupam Roy", "Shreya Ghoshal", "Jeet Gannguli", "Rupam Islam", "Shaan"],
    },
    videoQueries: {
      trending: "Bengali entertainment trending",
      latest: "Bengali movie trailers and clips",
      comedy: "Bengali standup and comedy skits",
      mindfulness: "Bengali meditation for calm mind",
      musicVideos: "Bengali latest music video releases",
      shorts: "Bengali viral shorts",
    },
    memeSources: {
      subreddits: ["bengalimemes", "kolkata"],
      searchTerms: ["bengali memes", "kolkata funny memes", "bangla memes"],
    },
  },
  mr: {
    code: "mr",
    name: "Marathi",
    nativeName: "मराठी",
    flag: "🇮🇳",
    musicQueries: {
      latest: "Marathi latest film songs",
      trending: "Marathi trending songs",
      popular: "Marathi all time popular songs",
      melodies: "Marathi bhavgeet and soft melodies",
      playlists: "Top Marathi Songs Playlist",
      artists: ["Ajay-Atul", "Avadhoot Gupte", "Swapnil Bandodkar", "Bela Shende", "Shreya Ghoshal", "Anand Shinde"],
    },
    videoQueries: {
      trending: "Marathi entertainment trending",
      latest: "Marathi movie trailers and songs",
      comedy: "Marathi comedy clips and standup",
      mindfulness: "Marathi dhyan and meditation",
      musicVideos: "Marathi official video songs",
      shorts: "Marathi funny shorts",
    },
    memeSources: {
      subreddits: ["marathimemes", "maharashtra", "mumbai", "pune"],
      searchTerms: ["marathi memes", "marathi funny memes", "puneri memes"],
    },
  },
  gu: {
    code: "gu",
    name: "Gujarati",
    nativeName: "ગુજરાતી",
    flag: "🇮🇳",
    musicQueries: {
      latest: "Gujarati latest songs and Garba",
      trending: "Gujarati trending viral songs",
      popular: "Gujarati folk and modern hits",
      melodies: "Gujarati romantic melodies",
      playlists: "Top Gujarati Hits Playlist",
      artists: ["Sachin-Jigar", "Aditya Gadhvi", "Kinjal Dave", "Geeta Rabari", "Jignesh Kaviraj", "Kirtidan Gadhvi"],
    },
    videoQueries: {
      trending: "Gujarati entertainment trending",
      latest: "Gujarati natak and movie trailers",
      comedy: "Gujarati standup comedy and jokes",
      mindfulness: "Gujarati meditation for mental peace",
      musicVideos: "Gujarati new video songs",
      shorts: "Gujarati viral shorts",
    },
    memeSources: {
      subreddits: ["gujaratimemes", "gujarat", "ahmedabad"],
      searchTerms: ["gujarati memes", "gujarati comedy memes", "gujju memes"],
    },
  },
  pa: {
    code: "pa",
    name: "Punjabi",
    nativeName: "ਪੰਜਾਬੀ",
    flag: "🇮🇳",
    musicQueries: {
      latest: "Punjabi latest music releases",
      trending: "Punjabi viral trending chartbusters",
      popular: "Punjabi all time party and pop hits",
      melodies: "Punjabi soulful romantic acoustic",
      playlists: "Top Punjabi Hits Playlist",
      artists: ["Diljit Dosanjh", "AP Dhillon", "Karan Aujla", "Sidhu Moose Wala", "Guru Randhawa", "Amrinder Gill", "Jasleen Royal"],
    },
    videoQueries: {
      trending: "Punjabi entertainment trending",
      latest: "Punjabi movie trailers and music videos",
      comedy: "Punjabi comedy movies clips and standup",
      mindfulness: "Peaceful Punjabi meditation music",
      musicVideos: "Punjabi official 4K music videos",
      shorts: "Punjabi viral shorts",
    },
    memeSources: {
      subreddits: ["punjabimemes", "punjabi", "chandigarh"],
      searchTerms: ["punjabi memes", "funny punjabi memes", "punjabi college memes"],
    },
  },
};

export function getLanguageConfig(langCode = "ta") {
  const code = (langCode || "ta").toLowerCase().trim();
  return ENTERTAINMENT_LANGUAGES[code] || ENTERTAINMENT_LANGUAGES["ta"];
}
