/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAccountSettingsRouteImport } from './routes/_authenticated/account-settings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppointmentRequestsRouteImport } from './routes/_authenticated/appointment-requests'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedAssessmentRouteImport } from './routes/_authenticated/assessment'
import { Route as AuthenticatedCompanionRouteImport } from './routes/_authenticated/companion'
import { Route as AuthenticatedCounsellorRouteImport } from './routes/_authenticated/counsellor'
import { Route as AuthenticatedCounsellorsRouteImport } from './routes/_authenticated/counsellors'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated/emergency'
import { Route as AuthenticatedEmergencyCasesRouteImport } from './routes/_authenticated/emergency-cases'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedWellbeingRouteImport } from './routes/_authenticated/wellbeing'
import { Route as AuthenticatedCallRoomIdRouteImport } from './routes/_authenticated/call.$roomId'
import { Route as AuthenticatedChatPeerIdRouteImport } from './routes/_authenticated/chat.$peerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountSettingsRoute =
  AuthenticatedAccountSettingsRouteImport.update({
    id: '/account-settings',
    path: '/account-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentRequestsRoute =
  AuthenticatedAppointmentRequestsRouteImport.update({
    id: '/appointment-requests',
    path: '/appointment-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentRoute = AuthenticatedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanionRoute = AuthenticatedCompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCounsellorRoute = AuthenticatedCounsellorRouteImport.update({
  id: '/counsellor',
  path: '/counsellor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCounsellorsRoute =
  AuthenticatedCounsellorsRouteImport.update({
    id: '/counsellors',
    path: '/counsellors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmergencyCasesRoute =
  AuthenticatedEmergencyCasesRouteImport.update({
    id: '/emergency-cases',
    path: '/emergency-cases',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWellbeingRoute = AuthenticatedWellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallRoomIdRoute = AuthenticatedCallRoomIdRouteImport.update({
  id: '/call/$roomId',
  path: '/call/$roomId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatPeerIdRoute = AuthenticatedChatPeerIdRouteImport.update({
  id: '/chat/$peerId',
  path: '/chat/$peerId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account-settings': typeof AuthenticatedAccountSettingsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/appointment-requests': typeof AuthenticatedAppointmentRequestsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/companion': typeof AuthenticatedCompanionRoute
  '/counsellor': typeof AuthenticatedCounsellorRoute
  '/counsellors': typeof AuthenticatedCounsellorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/emergency-cases': typeof AuthenticatedEmergencyCasesRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wellbeing': typeof AuthenticatedWellbeingRoute
  '/call/$roomId': typeof AuthenticatedCallRoomIdRoute
  '/chat/$peerId': typeof AuthenticatedChatPeerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account-settings': typeof AuthenticatedAccountSettingsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/appointment-requests': typeof AuthenticatedAppointmentRequestsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/companion': typeof AuthenticatedCompanionRoute
  '/counsellor': typeof AuthenticatedCounsellorRoute
  '/counsellors': typeof AuthenticatedCounsellorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/emergency-cases': typeof AuthenticatedEmergencyCasesRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wellbeing': typeof AuthenticatedWellbeingRoute
  '/call/$roomId': typeof AuthenticatedCallRoomIdRoute
  '/chat/$peerId': typeof AuthenticatedChatPeerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/account-settings': typeof AuthenticatedAccountSettingsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/appointment-requests': typeof AuthenticatedAppointmentRequestsRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/assessment': typeof AuthenticatedAssessmentRoute
  '/_authenticated/companion': typeof AuthenticatedCompanionRoute
  '/_authenticated/counsellor': typeof AuthenticatedCounsellorRoute
  '/_authenticated/counsellors': typeof AuthenticatedCounsellorsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
  '/_authenticated/emergency-cases': typeof AuthenticatedEmergencyCasesRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wellbeing': typeof AuthenticatedWellbeingRoute
  '/_authenticated/call/$roomId': typeof AuthenticatedCallRoomIdRoute
  '/_authenticated/chat/$peerId': typeof AuthenticatedChatPeerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/account-settings'
    | '/admin'
    | '/appointment-requests'
    | '/appointments'
    | '/assessment'
    | '/companion'
    | '/counsellor'
    | '/counsellors'
    | '/dashboard'
    | '/emergency'
    | '/emergency-cases'
    | '/journal'
    | '/messages'
    | '/onboarding'
    | '/settings'
    | '/wellbeing'
    | '/call/$roomId'
    | '/chat/$peerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/account-settings'
    | '/admin'
    | '/appointment-requests'
    | '/appointments'
    | '/assessment'
    | '/companion'
    | '/counsellor'
    | '/counsellors'
    | '/dashboard'
    | '/emergency'
    | '/emergency-cases'
    | '/journal'
    | '/messages'
    | '/onboarding'
    | '/settings'
    | '/wellbeing'
    | '/call/$roomId'
    | '/chat/$peerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/account-settings'
    | '/_authenticated/admin'
    | '/_authenticated/appointment-requests'
    | '/_authenticated/appointments'
    | '/_authenticated/assessment'
    | '/_authenticated/companion'
    | '/_authenticated/counsellor'
    | '/_authenticated/counsellors'
    | '/_authenticated/dashboard'
    | '/_authenticated/emergency'
    | '/_authenticated/emergency-cases'
    | '/_authenticated/journal'
    | '/_authenticated/messages'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/wellbeing'
    | '/_authenticated/call/$roomId'
    | '/_authenticated/chat/$peerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account-settings': {
      id: '/_authenticated/account-settings'
      path: '/account-settings'
      fullPath: '/account-settings'
      preLoaderRoute: typeof AuthenticatedAccountSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointment-requests': {
      id: '/_authenticated/appointment-requests'
      path: '/appointment-requests'
      fullPath: '/appointment-requests'
      preLoaderRoute: typeof AuthenticatedAppointmentRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment': {
      id: '/_authenticated/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthenticatedAssessmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companion': {
      id: '/_authenticated/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof AuthenticatedCompanionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/counsellor': {
      id: '/_authenticated/counsellor'
      path: '/counsellor'
      fullPath: '/counsellor'
      preLoaderRoute: typeof AuthenticatedCounsellorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/counsellors': {
      id: '/_authenticated/counsellors'
      path: '/counsellors'
      fullPath: '/counsellors'
      preLoaderRoute: typeof AuthenticatedCounsellorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emergency-cases': {
      id: '/_authenticated/emergency-cases'
      path: '/emergency-cases'
      fullPath: '/emergency-cases'
      preLoaderRoute: typeof AuthenticatedEmergencyCasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wellbeing': {
      id: '/_authenticated/wellbeing'
      path: '/wellbeing'
      fullPath: '/wellbeing'
      preLoaderRoute: typeof AuthenticatedWellbeingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/call/$roomId': {
      id: '/_authenticated/call/$roomId'
      path: '/call/$roomId'
      fullPath: '/call/$roomId'
      preLoaderRoute: typeof AuthenticatedCallRoomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$peerId': {
      id: '/_authenticated/chat/$peerId'
      path: '/chat/$peerId'
      fullPath: '/chat/$peerId'
      preLoaderRoute: typeof AuthenticatedChatPeerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountSettingsRoute: typeof AuthenticatedAccountSettingsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppointmentRequestsRoute: typeof AuthenticatedAppointmentRequestsRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAssessmentRoute: typeof AuthenticatedAssessmentRoute
  AuthenticatedCompanionRoute: typeof AuthenticatedCompanionRoute
  AuthenticatedCounsellorRoute: typeof AuthenticatedCounsellorRoute
  AuthenticatedCounsellorsRoute: typeof AuthenticatedCounsellorsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
  AuthenticatedEmergencyCasesRoute: typeof AuthenticatedEmergencyCasesRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWellbeingRoute: typeof AuthenticatedWellbeingRoute
  AuthenticatedCallRoomIdRoute: typeof AuthenticatedCallRoomIdRoute
  AuthenticatedChatPeerIdRoute: typeof AuthenticatedChatPeerIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountSettingsRoute: AuthenticatedAccountSettingsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppointmentRequestsRoute: AuthenticatedAppointmentRequestsRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAssessmentRoute: AuthenticatedAssessmentRoute,
  AuthenticatedCompanionRoute: AuthenticatedCompanionRoute,
  AuthenticatedCounsellorRoute: AuthenticatedCounsellorRoute,
  AuthenticatedCounsellorsRoute: AuthenticatedCounsellorsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedEmergencyCasesRoute: AuthenticatedEmergencyCasesRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWellbeingRoute: AuthenticatedWellbeingRoute,
  AuthenticatedCallRoomIdRoute: AuthenticatedCallRoomIdRoute,
  AuthenticatedChatPeerIdRoute: AuthenticatedChatPeerIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
